export { default as Login } from "./src/components/auth/Login";
export { default as Dashboard } from "./src/pages/Dashborad";
export { default as Students } from "./src/pages/Students";
export { default as StudentAdd } from "./src/Features/students/StudentAdd"
export { default as StudentDelete } from "./src/Features/students/StudentDelete"
export { default as StudentEdit } from "./src/Features/students/StudentEdit"
export { default as Rooms } from "./src/pages/Rooms";
export { default as RoomAdd } from "./src/Features/rooms/RoomAdd"
export { default as RoomDelete } from "./src/Features/rooms/RoomDelete"
export { default as RoomEdit } from "./src/Features/rooms/RoomEdit"
export { default as Managers } from "./src/pages/Managers";
export { default as ManagerAdd } from "./src/Features/managers/ManagerAdd";
export { default as ManagerEdit } from "./src/Features/managers/ManagerEdit";
export { default as ManagerDalete } from "./src/Features/managers/ManagerDelete";
export { default as Groups } from "./src/pages/Groups";
export { default as GroupAdd } from "./src/Features/groups/GroupsAdd";
export { default as GroupEdit } from "./src/Features/groups/GroupEdit";
export { default as GroupDelete } from "./src/Features/groups/GroupDelete";
export { default as Teachers } from "./src/pages/Teachers"
export { default as TeacherAdd } from "./src/Features/teachers/TeacherAdd"
export { default as TeacherDelete } from "./src/Features/teachers/TeacherDelete"
export { default as TeacherEdit } from "./src/Features/teachers/TeacherEdit"